# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Deploy Infrastructure

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GITHUB_USER: ${{ secrets.GITHUB_USER }}
jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pauldaniv/yellow-taxi-scripts/build:latest
#      credentials:
#        username: ${GITHUB_USER:-${{ github.actor }}}
#        password: ${{ secrets.GITHUB_TOKEN }}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sync
        run: terraform init && terraform apply --auto-approve && terraform destroy --auto-approve
